import type { Metadata } from "next";
import "./globals.css";
import { Geist_Mono } from "next/font/google";

const geistMono = Geist_Mono({
  subsets: ["latin"],
  weight: ["400", "700"], // or ['100', '200', ..., '900']
  display: "swap",
});

export const metadata: Metadata = {
  title: "Next Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistMono.className}>{children}</body>
    </html>
  );
}
